### ISSUE TITLE
Create a signup and login page.

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#17]
create signup and login page with minimal and responsive ui.

**Comment by Trisha-tech** [comment]
Hello @firtysh, I would like to work on this issue under JWOC 2023.

**Comment by firtysh** [comment]
> Hello @firtysh, I would like to work on this issue under JWOC 2023.

Assigned

**Comment by mecivil** [comment]
I want to take up this issue under JWOC
