### ISSUE TITLE
Migrate to ejs template engine.

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#18]
Use ejs template engine to render the pages instead of raw html

**Comment by mecivil** [comment]
I am ready to take up this issue but please provide JWOC and difficulty label.

**Comment by firtysh** [comment]
> I am ready to take up this issue but please provide JWOC and difficulty label.

I haven't yet decided to put this issue up for JWOC. If i do then I will let you know.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by firtysh** [comment]
> I want to work for on this issue under jwoc , please assign me

Hritik I kept this issue for phase 2, i will start assigning this issue after phase 2 begins

**Comment by pooranjoyb** [comment]
I would like to work on this issue @firtysh

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by firtysh** [comment]
> I would like to work on this issue @firtysh

Assigned
