### ISSUE TITLE
create landing page

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#2]
Create a landing page for "/" endpoint.

**Comment by Arbtrage** [comment]
Would like to work on this ...

**Comment by PARASnagpal99** [comment]
I would like to work on it sir .

**Comment by loki1205** [comment]
Hi, can anyone tell me the meaning of "/" endpoint? Does that mean a landing page for the Homepage of the website?

**Comment by Arbtrage** [comment]
Basically it is a server endpoint which would send some response with respect to the request sent by the user.
In this case it would be a get request and the response from the server would be the homepage of this application.

**Comment by firtysh** [comment]
> Would like to work on this ...

The issues will be assigned from 15th February on a first come first serve basis. Any comment before 15th February will be considered invalid. Though you can ask your doubts or queries.

**Comment by adityakhattri21** [comment]
I would like to work on this issue please.

**Comment by singhalaman23** [comment]
"I want to work on this issue under JWOC"

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me under JWOC .

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
I want to work on this issue under JWOC

**Comment by firtysh** [comment]
> I would like to work on this issue please.

I have assigned the issue to you now you can work on it.
