### ISSUE TITLE
README file needs to get updated

### ISSUE THREAD

**Issue by Code1705** [firtysh/real-time-file-share#23]

**Comment by firtysh** [comment]
@Code1705  what changes would you like to make?

**Comment by Code1705** [comment]
I suppose there should be more detailing about the app as such more content.

**Comment by firtysh** [comment]
> I suppose there should be more detailing about the app as such more content.

What else you want to add?

**Comment by Code1705** [comment]
as such more info that what the app is about briefly and features  and also the contributing process to be elaborated more.

**Comment by firtysh** [comment]
@Code1705  Assigned

**Comment by firtysh** [comment]
> @Code1705 Assigned

@Code1705  Since you havent made any pr i have to unassign you.

**Comment by neokd** [comment]
Can i work on this issue under JWOC

**Comment by Code1705** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/116907909/219856207-97023bee-df21-4563-b0fd-1610c02801a8.png)
I have already issued a PR an hour ago before your message , please have a look

**Comment by firtysh** [comment]
> ![Screenshot (29)](https://user-images.githubusercontent.com/116907909/219856207-97023bee-df21-4563-b0fd-1610c02801a8.png)
> I have already issued a PR an hour ago before your message , please have a look
> 

Ohh. It wasn't visible when i checked. I'll merge it.
