### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by tmsagarofficial** [firtysh/real-time-file-share#26]
I wanted to let u know that i would love to fix these small bugs/render issues in the markdown `README.md`  under jwoc

![image](https://user-images.githubusercontent.com/110724849/220173603-f5e766db-99e9-40af-ba06-e8c1cf9b337c.png)

also
![image](https://user-images.githubusercontent.com/110724849/220173668-f09666ed-21d4-41c2-879a-21cdbefd4178.png)

Pls let me know about the same @firtysh

**Comment by tmsagarofficial** [comment]
Also i wanted to ask if i could help in adding some screenshots of the project which would make it more infomrative

**Comment by firtysh** [comment]
> I wanted to let u know that i would love to fix these small bugs/render issues in the markdown `README.md` under jwoc
> 
> ![image](https://user-images.githubusercontent.com/110724849/220173603-f5e766db-99e9-40af-ba06-e8c1cf9b337c.png)
> 
> also ![image](https://user-images.githubusercontent.com/110724849/220173668-f09666ed-21d4-41c2-879a-21cdbefd4178.png)
> 
> Pls let me know about the same @firtysh

Assigned

**Comment by tmsagarofficial** [comment]
Hey @firtysh Thanks for assigning this issue to me and allowing mw to work on this issue .


Also
PLs check this ' Pull Request #27 ` Pull request #27

**Comment by tmsagarofficial** [comment]
Thanks 👍🏼
