### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by thevinitgupta** [firtysh/real-time-file-share#28]
The website breaks on smaller screens.

It would be better for the website to responsive so that users can use it on mobile also.
![Screen Shot 2023-02-22 at 11 42 36](https://user-images.githubusercontent.com/65801700/220537945-4631ea94-2aba-4eab-825c-5d53c1dd18c9.png)
![Screen Shot 2023-02-22 at 11 42 29](https://user-images.githubusercontent.com/65801700/220537958-72e5b132-4e7d-453e-80cc-75c4592a06f0.png)

I would love to work on this.

**Comment by VaibhavTalkhande** [comment]
can you assign it to me under Jwoc

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by firtysh** [comment]
> The website breaks on smaller screens.
> 
> It would be better for the website to responsive so that users can use it on mobile also. ![Screen Shot 2023-02-22 at 11 42 36](https://user-images.githubusercontent.com/65801700/220537945-4631ea94-2aba-4eab-825c-5d53c1dd18c9.png) ![Screen Shot 2023-02-22 at 11 42 29](https://user-images.githubusercontent.com/65801700/220537958-72e5b132-4e7d-453e-80cc-75c4592a06f0.png)
> 
> I would love to work on this.

Assigned

**Comment by thevinitgupta** [comment]
Thanks I will start working on it.

**Comment by Awesomeasma** [comment]
@firtysh 
I would like to work on this issue under JWOC.

**Comment by firtysh** [comment]
> @firtysh I would like to work on this issue under JWOC.

Assigned
