### ISSUE TITLE
Add click to copy feature for room id

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#3]
![Screenshot from 2023-02-12 22-54-09](https://user-images.githubusercontent.com/77226097/218326721-8e0d9773-d088-44cb-bd70-e9b70a65c691.png)
implement a feature to copy the room id on click.

**Comment by RishabhJain0721** [comment]
I want to work under this issue under JWOC.

**Comment by singhalaman23** [comment]
"I want to work on this issue under JWOC"

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me under JWOC .

**Comment by firtysh** [comment]
> I want to work under this issue under JWOC.

I have assigned the issue to you. Now you can work on it.
