### ISSUE TITLE
Improving Responsiveness

### ISSUE THREAD

**Issue by Beingfarazkhan** [firtysh/real-time-file-share#30]
Responsivity for the website is not maintained and i would like to make it more mobile friendly because most of the transfers take place using mobile phones 
it would be hard to take care of the images but i will try to manage it
![Screenshot (1301)](https://user-images.githubusercontent.com/97282347/220989256-a67cdf58-1ad4-442e-a712-c8827ba75100.png)

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by firtysh** [comment]
> Responsivity for the website is not maintained and i would like to make it more mobile friendly because most of the transfers take place using mobile phones it would be hard to take care of the images but i will try to manage it ![Screenshot (1301)](https://user-images.githubusercontent.com/97282347/220989256-a67cdf58-1ad4-442e-a712-c8827ba75100.png)

Simmilar issue is already created #28
