### ISSUE TITLE
Configure mongodb connection and create a schema for user with respect to the fields in sign up page

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#33]

**Comment by Laxmankohar** [comment]
Hey @firtysh , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by firtysh** [comment]
> Hey @firtysh , I would like to work on this issue under JWOC. Can you please assign it to me?

Assigned

**Comment by Laxmankohar** [comment]
Hey @firtysh , Could you please check it? 
![image](https://user-images.githubusercontent.com/73365025/221352164-4ca9537c-bc61-4d57-b060-a8ba0c9d440d.png)

**Comment by firtysh** [comment]
> Hey @firtysh , Could you please check it? ![image](https://user-images.githubusercontent.com/73365025/221352164-4ca9537c-bc61-4d57-b060-a8ba0c9d440d.png)

You dont need to create a different server.js write your code in the existing index.js and for the scema create a seperate folder called models

**Comment by Laxmankohar** [comment]
ok

**Comment by Laxmankohar** [comment]
@firtysh , confirm it sothat i can make PR.

![image](https://user-images.githubusercontent.com/73365025/221367793-0125a8e9-5885-4d6c-b22d-96ae5754009e.png)

**Comment by Laxmankohar** [comment]
confirm it bro.

**Comment by firtysh** [comment]
> confirm it bro.

Make the pr so i can check the code
