### ISSUE TITLE
Improving Ui

### ISSUE THREAD

**Issue by Beingfarazkhan** [firtysh/real-time-file-share#37]
Would like to improve the recievers page UI
![Screenshot (1302)](https://user-images.githubusercontent.com/97282347/221343840-fd336ae5-68be-4c1e-93f9-78d817cd83e6.png)

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by firtysh** [comment]
> Would like to improve the recievers page UI ![Screenshot (1302)](https://user-images.githubusercontent.com/97282347/221343840-fd336ae5-68be-4c1e-93f9-78d817cd83e6.png)

Assigned

**Comment by Code1705** [comment]
I want to contribute to this issue , please assign me under JWOC

**Comment by Beingfarazkhan** [comment]
@firtysh 
can you check and review this pls, if you want any addition please do tell.
![Screenshot (1304)](https://user-images.githubusercontent.com/97282347/222235933-14e00789-781e-48cf-87fe-b21426b8b281.png)

**Comment by Code1705** [comment]
I want to make it attractive and stylish , please assign me this issue under JWOC.
