### ISSUE TITLE
text visibility fix.

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#4]
![Screenshot from 2023-02-12 23-01-39](https://user-images.githubusercontent.com/77226097/218327040-d0e97f13-bc44-4706-b060-9d743b20638d.png)
Make the texts here more visible

**Comment by mecivil** [comment]
Hello  ,
I want to work on this issue being a mentee in JWOC.
Please assign me with this issue as a part of JWOC.

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me under JWOC .

**Comment by firtysh** [comment]
> Hello , I want to work on this issue being a mentee in JWOC. Please assign me with this issue as a part of JWOC.

I have assigned the issue to you. Now you can work on it.

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"
