### ISSUE TITLE
Designing of navbar

### ISSUE THREAD

**Issue by Laxmankohar** [firtysh/real-time-file-share#44]
I want to work on this issue under JWOC. Can you please assign it to me?

![image](https://user-images.githubusercontent.com/73365025/221471185-636e76b0-3e94-46a7-8444-d3392b87e0fb.png)

**Comment by firtysh** [comment]
> I want to work on this issue under JWOC. Can you please assign it to me?
> 
> ![image](https://user-images.githubusercontent.com/73365025/221471185-636e76b0-3e94-46a7-8444-d3392b87e0fb.png)

Fixed by #46
