### ISSUE TITLE
Improving the UI of contact us page

### ISSUE THREAD

**Issue by ManasaKaza** [firtysh/real-time-file-share#49]
![image](https://user-images.githubusercontent.com/122222373/222637632-aa538bb2-9822-4eff-8095-f055cfc5467f.png)
In this page the padding and all doesn't make it look good, I would like to improve it's UI.
I want to work on this issue under JWOC

**Comment by firtysh** [comment]
> ![image](https://user-images.githubusercontent.com/122222373/222637632-aa538bb2-9822-4eff-8095-f055cfc5467f.png) In this page the padding and all doesn't make it look good, I would like to improve it's UI. I want to work on this issue under JWOC

will be fixed by #50
