### ISSUE TITLE
Create a navbar 

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#5]
Create a navigation bar with Home, Send, Receive and about buttons.

**Comment by KrunalGupta02** [comment]
hi i would like to work on this issue kindly assign me this problem. #jwoc

**Comment by firtysh** [comment]
> hi i would like to work on this issue kindly assign me this problem. #jwoc

Hello krunal, the contributing period starts from 15th feb. I can not assign any issue till then. And any comment before 15 th feb will be considered invalid.

**Comment by Biswajit-Behera** [comment]
> > hi i would like to work on this issue kindly assign me this problem. #jwoc
> 
> Hello krunal, the contributing period starts from 15th feb. I can not assign any issue till then. And any comment before 15 th feb will be considered invalid.

So comment on or after 15th Feb are valid??

**Comment by firtysh** [comment]
> > > hi i would like to work on this issue kindly assign me this problem. #jwoc
> > 
> > 
> > Hello krunal, the contributing period starts from 15th feb. I can not assign any issue till then. And any comment before 15 th feb will be considered invalid.
> 
> So comment on or after 15th Feb are valid??

Yes

**Comment by Awesomeasma** [comment]
I want to work on this issue under JWOC

**Comment by Biswajit-Behera** [comment]
I want to work on this issue under JWOC.

**Comment by KrunalGupta02** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
I want to work on this issue under JWOC

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by firtysh** [comment]
> I want to work on this issue under JWOC

I have assigned the issue to you. Now you can work on it.

**Comment by AgnishaDe** [comment]
I want to work on this issue under jwoc

**Comment by Awesomeasma** [comment]
> > I want to work on this issue under JWOC
> 
> I have assigned the issue to you. Now you can work on it.

Thank you..

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"

**Comment by firtysh** [comment]
> I want to work on this issue under JWOC.

Assigned to you

**Comment by firtysh** [comment]
@Awesomeasma  I have unassigned you since you didn't make any pr.

**Comment by KrunalGupta02** [comment]
> @Awesomeasma  I have unassigned you since you didn't make any pr.

 Can i work on it

**Comment by Biswajit-Behera** [comment]
@firtysh Thank You, will give you update ASAP!
Sorry for the late response.

**Comment by Biswajit-Behera** [comment]
@firtysh created the PR!
If any conflict occurs let me know.

**Comment by firtysh** [comment]
> @firtysh created the PR! If any conflict occurs let me know.

Follow the pull request template and mention the issue no. Add screenshots of the change.

**Comment by Biswajit-Behera** [comment]
Issue No.- #5
PR - #22 

Reciver Side:-
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/219437071-9a0e8402-07fc-4b55-96ab-9a2fd13d485d.png">

Sender Side:-
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/219436714-27c2ae38-f028-469b-b129-5e1b31658fdc.png">

Home Side:-
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/219437301-3cd2536e-275f-43ab-9b21-2870db053168.png">

**Comment by firtysh** [comment]
> Issue No.- #5 PR - #22
> 
> Reciver Side:- <img alt="image" width="1440" src="https://user-images.githubusercontent.com/86191708/219437071-9a0e8402-07fc-4b55-96ab-9a2fd13d485d.png">
> 
> Sender Side:- <img alt="image" width="1440" src="https://user-images.githubusercontent.com/86191708/219436714-27c2ae38-f028-469b-b129-5e1b31658fdc.png">
> 
> Home Side:- <img alt="image" width="1440" src="https://user-images.githubusercontent.com/86191708/219437301-3cd2536e-275f-43ab-9b21-2870db053168.png">

Remove the search bar and make the navbar style of the receive page same as other two pages

**Comment by Biswajit-Behera** [comment]
Will do!

**Comment by Biswajit-Behera** [comment]
Just Check the screenshot then I will create PR.
Reciver:-
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/219445282-89a5898d-0f5b-44ba-99f2-57d6b25c7bd0.png">

Sender:-
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/219445368-538d75ee-a6fd-4cba-890e-e4219d20a0a0.png">

Home:-
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/219445556-6817232e-f4f3-434c-9027-9a072042a394.png">

**Comment by Biswajit-Behera** [comment]
@firtysh If you find any improvent in the above screenshots, letmme know!

**Comment by firtysh** [comment]
> @firtysh If you find any improvent in the above screenshots, letmme know!

Cool now push the changes and edit the pr you have made

**Comment by Biswajit-Behera** [comment]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/86191708/219505811-8493ddbf-7348-4987-b887-2d95fa0ad5e5.png">
@firtysh here conflicts occurs! What should I do?

**Comment by Biswajit-Behera** [comment]
I tried to change couple of things but unable to solve the conflicts.

**Comment by KrunalGupta02** [comment]
>  I tried to change couple of things but unable to solve the conflicts.

Did u make a new branch before committing ?

**Comment by Biswajit-Behera** [comment]
> > I tried to change couple of things but unable to solve the conflicts.
> 
> Did u make a new branch before committing ?

Igs No!
Can we edit existing PR with new branch?

**Comment by firtysh** [comment]
> > > I tried to change couple of things but unable to solve the conflicts.
> > 
> > 
> > Did u make a new branch before committing ?
> 
> Igs No! Can we edit existing PR with new branch?

did ypu push the chnage?

**Comment by Biswajit-Behera** [comment]
> existing

Yes!

**Comment by firtysh** [comment]
> > existing
> 
> Yes!

Edit the pull request and add screenshots in the pull request not here
