### ISSUE TITLE
Create uniform theme across all the pages using any css framework or custom css

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#50]

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by ritika728** [comment]
Hey, I can work on this issue under JWOC

**Comment by firtysh** [comment]
> I want to work on this issue under JWOC

Assigned

**Comment by pooranjoyb** [comment]
Hey, I would love to work on this issue. @firtysh

**Comment by firtysh** [comment]
> Hey, I can work on this issue under JWOC

Assigned

**Comment by ManasaKaza** [comment]
@firtysh I made a PR right, you told me to modify just 3 minutes back after giving it a review and you did not even gave me a chance to modify

**Comment by firtysh** [comment]
> @firtysh I made a PR right, you told me to modify just 3 minutes back after giving it a review and you did not even gave me a chance to modify
I assigned it to you 5 days back and you made the pr on the last day. And in the issue i clearly mentioned to change all the pages but you changed only few pages. The maximum time limit for a hard issue is 4 days but you don't have any time left so i closed the pr.

**Comment by ManasaKaza** [comment]
@firtysh Fine!!

**Comment by ManasaKaza** [comment]
> > @firtysh I made a PR right, you told me to modify just 3 minutes back after giving it a review and you did not even gave me a chance to modify
> > I assigned it to you 5 days back and you made the pr on the last day. And in the issue i clearly mentioned to change all the pages but you changed only few pages. The maximum time limit for a hard issue is 4 days but you don't have any time left so i closed the pr.

I have modified all the pages except the homepage

**Comment by firtysh** [comment]
> > > @firtysh I made a PR right, you told me to modify just 3 minutes back after giving it a review and you did not even gave me a chance to modify
> > > I assigned it to you 5 days back and you made the pr on the last day. And in the issue i clearly mentioned to change all the pages but you changed only few pages. The maximum time limit for a hard issue is 4 days but you don't have any time left so i closed the pr.
> 
> I have modified all the pages except the homepage

Its not just that you haven't modified homepage. you should have used same fonts for all the titles, same font for all the text content, some color scheme and there are lot of things like that.
