### ISSUE TITLE
Improve file system for connecting mongoDB

### ISSUE THREAD

**Issue by AbhiPatel10** [firtysh/real-time-file-share#51]
We Should Improve the file system to connect with mongoDb

MongoDb Page Should be separate and Mongo URL should come from .env file or another config file.

![image](https://user-images.githubusercontent.com/76242769/222812793-c8331ead-1490-4cc4-9577-5302f472fa20.png)

Please assign this issue to me Under JWOC

**Comment by firtysh** [comment]
> We Should Improve the file system to connect with mongoDb
> 
> MongoDb Page Should be separate and Mongo URL should come from .env file or another config file.
> 
> ![image](https://user-images.githubusercontent.com/76242769/222812793-c8331ead-1490-4cc4-9577-5302f472fa20.png)
> 
> Please assign this issue to me Under JWOC

Assigned
