### ISSUE TITLE
Put Navbar in Receive page too

### ISSUE THREAD

**Issue by AbhiPatel10** [firtysh/real-time-file-share#52]
![image](https://user-images.githubusercontent.com/76242769/222813570-e77b4f30-44a7-49bf-aa92-80e7dba72a12.png)

Please assign this issue to me under JWOC

**Comment by firtysh** [comment]
> ![image](https://user-images.githubusercontent.com/76242769/222813570-e77b4f30-44a7-49bf-aa92-80e7dba72a12.png)
> 
> Please assign this issue to me under JWOC

will be fixed bt #50
