### ISSUE TITLE
UI Overflowing

### ISSUE THREAD

**Issue by suman-tewary** [firtysh/real-time-file-share#54]
Button text and other elements overflows from their actual position
<img width="951" alt="image" src="https://user-images.githubusercontent.com/43510749/222981245-04f55479-2992-45c0-a31d-cd0c75c4a2ca.png">

**Comment by firtysh** [comment]
> Button text and other elements overflows from their actual position <img alt="image" width="951" src="https://user-images.githubusercontent.com/43510749/222981245-04f55479-2992-45c0-a31d-cd0c75c4a2ca.png">

Will be fixed by #50
