### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by JasonDsouza212** [firtysh/real-time-file-share#55]
- It would be beneficial if all the pages had the navbar. It would be beneficial if all the pages have the navbar
- When you go to another page, you get stuck because there's no navbar and you can only go back by using the back button.
- Therefore, it would be good to have a navbar on all pages.
- The contact button is not navigating anywhere.

**Comment by firtysh** [comment]
> * It would be beneficial if all the pages had the navbar. It would be beneficial if all the pages have the navbar
> * When you go to another page, you get stuck because there's no navbar and you can only go back by using the back button.
> * Therefore, it would be good to have a navbar on all pages.
> * The contact button is not navigating anywhere.

I got your point but the ui will be fixed by #50 . I think if you create the issue after #50  gets resolved then it will be more appropriate.
