### ISSUE TITLE
Design receive page

### ISSUE THREAD

**Issue by firtysh** [firtysh/real-time-file-share#6]
Design the receive page and make it responsive

**Comment by Suniti-0020** [comment]
hi @firtysh  I would like to work on the issue . 
Can you assign it to me.  under JWOC

**Comment by Aniket-011** [comment]
I want to work on this issue under JWOC

**Comment by firtysh** [comment]
> hi @firtysh I would like to work on the issue . Can you assign it to me. under JWOC

I have assigned the issue to you. Now you can work on it.

**Comment by Suniti-0020** [comment]
Sir what is your discord channel name... 
I would like connect to you there ....

**Comment by firtysh** [comment]
> Sir what is your discord channel name... I would like connect to you there ....

Suman. There is a dedicated channel for this project named real time file share. Please check it out
