### ISSUE TITLE
Correction in Spelling of Receivers

### ISSUE THREAD

**Issue by ritika728** [firtysh/real-time-file-share#9]
Hey, I want to open this issue under JWOC.
The spelling of Receivers is mentioned as Recievers on the website, I would like to correct that.

**Comment by firtysh** [comment]
> Hey, I want to open this issue under JWOC. The spelling of Receivers is mentioned as Recievers on the website, I would like to correct that.

Assigned.

**Comment by AgnishaDe** [comment]
I want to work on this issue under JWOC
